export const SECONDS_PER_MINUTE = 60;
export const WORK_DURATION_SECONDS = 25 * SECONDS_PER_MINUTE;
export const SHORT_BREAK_DURATION_SECONDS = 5 * SECONDS_PER_MINUTE;
export const LONG_BREAK_DURATION_SECONDS = 15 * SECONDS_PER_MINUTE;
export const MAX_CYCLE_COUNT = 4;
export const LOW_ALARM_THRESHOLD_SECONDS = 3;
