name: Vite+ Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      # https://github.com/voidzero-dev/setup-vp
      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - run: vp test --coverage
